version: 2
updates:
  - package-ecosystem: composer
    directory: /
    target-branch: master
    open-pull-requests-limit: 30
    labels:
      - 'Dependencies'
      - 'PHP'
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    target-branch: master
    open-pull-requests-limit: 30
    labels:
      - 'Dependencies'
      - 'JS'
    schedule:
      interval: daily
    registries:
      - fontawesome

registries:
  fontawesome:
    type: npm-registry
    url: https://npm.fontawesome.com/
    token: ${{secrets.FONTAWESOME_NPM_AUTH_TOKEN}}
