doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: pdo_mysql
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        types:
            datetime_utc: App\Doctrine\DBAL\Types\DateTimeUTCType
            uuid: Ramsey\Uuid\Doctrine\UuidType

    orm:
        auto_mapping: true
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        quote_strategy: doctrine.orm.quote_strategy.ansi
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: App\Entity
                alias: App
