framework:
    rate_limiter:
        api:
            policy: 'sliding_window'
            limit: 450
            interval: '1 minute'
            cache_pool: rate_limiter.api_cache_pool

    cache:
        pools:
            rate_limiter.api_cache_pool:
                adapter: cache.adapter.redis
