webpack_encore:
    crossorigin: 'anonymous'
    output_path: '%kernel.project_dir%/public/assets'
    preload: true

    link_attributes:
        defer: true

    script_attributes:
        defer: true
