version: '3.7'

services:
    mysql:
        image: whatisflying/mysql:8.0
        build: docker/mysql
        container_name: whatisflying-mysql
        environment:
            MYSQL_DATABASE: db_name
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_password
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - /var/lib/mysql
        ports:
            - 3306:3306
        networks:
            internal:
                ipv4_address: 172.8.1.2

    nginx:
        image: whatisflying/nginx:1.19
        build: docker/nginx
        container_name: whatisflying-nginx
        working_dir: /usr/share/nginx/html
        volumes:
            - ./:/usr/share/nginx/html
            - ./config/jwt:/usr/share/nginx/html/config/jwt
        ports:
            - 80:80
            - 443:443
        networks:
            internal:
                ipv4_address: 172.8.1.3

    php:
        image: whatisflying/php:8.0
        build: docker/php
        container_name: whatisflying-php
        working_dir: /usr/share/nginx/html
        volumes:
            - ./:/usr/share/nginx/html
            - ./config/jwt:/usr/share/nginx/html/config/jwt
        networks:
            internal:
                ipv4_address: 172.8.1.4
        extra_hosts:
            mysql: 172.8.1.2
            redis: 172.8.1.6

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0
        container_name: whatisflying-phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - 3307:80
        networks:
            internal:
                ipv4_address: 172.8.1.5

    redis:
        image: redis:6.0
        container_name: whatisflying-redis
        volumes:
            - /data
        networks:
            internal:
                ipv4_address: 172.8.1.6

networks:
    internal:
        name: whatisflying
        ipam:
            driver: default
            config:
                -   subnet: 172.8.1.0/24
