services:
    Symfony\Component\Mailer\EventListener\EnvelopeListener:
        class: Symfony\Component\Mailer\EventListener\EnvelopeListener
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            $sender: null
            $recipients: [ '%env(MAILER_RECIPIENT_ADDRESS)%' ]
